### ISSUE TITLE
Spelling errors and some other small issues

### ISSUE THREAD

**Issue by dikarika** [andreanespeca/StarBreach#1]
Just pointing out a few spelling errors, all found in the export to PDF:

"Attach Roll Per Target" should say "Attack Roll Per Target"

Some descriptions have words with random hyphens. As an example, Pestilence Grenade has the word "disregard" hyphenated as "disre-gard". There are other examples, I can try to find them all if needed.

Also, I didn't see a file for Nomadic Raiders.

Keep up the good work!

**Comment by andreanespeca** [comment]
Thanks this is exactly how to report an issue! great thanks
i have fixed the attach per Terget in attack, are there other spelling error apart from this?
I'm aware of the hyphens word i'm afraid it's a copy and paste from the rulebook will fix those in a later date when everything is in place and up to date, will give priority to add missing warbands and finishing the updating to the latest rulebook. And yes nomadic raiders and resistance will be soon released it's just that they are a lot of work to do lol
THanks again please feel free to report other mistakes
I keep this issue open to remind me to fix the Hyphens!

**Comment by dikarika** [comment]
The "attach" spelling error still exists under Grenades. Also, the Continuum Clairvoyant should have some method to add plasmids at cost.

But that should be after Raiders and Resistance. No rush. Thanks for all the hard work.

**Comment by andreanespeca** [comment]
Grenades spelling error fixed as well.
Updated continuum syndicate warband to latest revision of rulebook including add plasmids at costs
Thanks for your help!
